os:
    - osx
    - linux
osx_image:  xcode12.2
python:
    - "3.7"
    - "3.8"
    - "3.9"
install: 
    - pip install -U pip
    - pip install -r requirements.txt
    - pip install .
script:
    - coverage run -m pytest tests/
branches:
    only:
    - master
after_success:
    - bash <(curl -s https://codecov.io/bash)
